"""Generate the colormap lookup-table module used by the playgrounds.

Reads matplotlib's `viridis`, `cividis`, and `RdBu_r` at 256 evenly spaced
points in [0, 1] and writes them as Uint8 LUTs in
shared/js/render/colormaps.js. The runtime sampling routine does linear
interpolation between adjacent LUT entries, so the perceptual fidelity is
within 1 unit per channel of matplotlib's reference at any t.

Usage: uv run python scripts/py/gen_colormaps.py
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
import matplotlib.cm as mcm
import numpy as np


def sample_cmap(name: str, n: int = 256) -> np.ndarray:
    cmap = mcm.get_cmap(name)
    ts = np.linspace(0.0, 1.0, n)
    rgba = cmap(ts)
    rgb = (rgba[:, :3] * 255.0).round().astype(np.int64).clip(0, 255).astype(np.uint8)
    return rgb


def lut_to_js(rgb: np.ndarray, var: str) -> str:
    triples = ",".join(f"{r},{g},{b}" for r, g, b in rgb)
    return f"const {var} = new Uint8Array([{triples}]);"


def emit(out_path: Path) -> None:
    viridis = sample_cmap("viridis")
    cividis = sample_cmap("cividis")
    rdbu_r  = sample_cmap("RdBu_r")
    header = (
        "// Perceptually uniform colormaps. Generated by scripts/py/gen_colormaps.py;\n"
        "// do not edit by hand. Each LUT is 256 entries x 3 bytes (R, G, B).\n"
        f"// Source: matplotlib {matplotlib.__version__}; viridis, cividis, RdBu_r.\n\n"
    )
    body = "\n".join([
        lut_to_js(viridis, "VIRIDIS_LUT"),
        lut_to_js(cividis, "CIVIDIS_LUT"),
        lut_to_js(rdbu_r,  "RDBU_R_LUT"),
    ])
    sampler = '''
function sampleLUT(lut, t) {
  // Linear interpolation between two adjacent 256-entry triples.
  const x = Math.max(0, Math.min(1, t)) * 255;
  const i = Math.floor(x);
  const f = x - i;
  const i0 = i * 3;
  const i1 = i === 255 ? i0 : i0 + 3;
  const r = Math.round(lut[i0]     + (lut[i1]     - lut[i0])     * f);
  const g = Math.round(lut[i0 + 1] + (lut[i1 + 1] - lut[i0 + 1]) * f);
  const b = Math.round(lut[i0 + 2] + (lut[i1 + 2] - lut[i0 + 2]) * f);
  return { r, g, b };
}

export function viridis(t) { return sampleLUT(VIRIDIS_LUT, t); }
export function cividis(t) { return sampleLUT(CIVIDIS_LUT, t); }
export function rdbu(t)    { return sampleLUT(RDBU_R_LUT, t); }

// Write a scalar field into ImageData using a chosen colormap.
// field: Float32Array or Float64Array of length width*height
// vmin, vmax: scaling
// cmap: function (t) -> {r,g,b}
export function fieldToImageData(field, width, height, vmin, vmax, cmap = viridis, imageData = null) {
  imageData = imageData ?? new ImageData(width, height);
  const data = imageData.data;
  const range = vmax - vmin || 1;
  for (let i = 0; i < field.length; i += 1) {
    const t = (field[i] - vmin) / range;
    const c = cmap(t);
    const j = i * 4;
    data[j]     = c.r;
    data[j + 1] = c.g;
    data[j + 2] = c.b;
    data[j + 3] = 255;
  }
  return imageData;
}

export const COLORMAPS = { viridis, cividis, rdbu };
'''
    out_path.write_text(header + body + sampler)


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[2]
    target = root / "shared" / "js" / "render" / "colormaps.js"
    emit(target)
    print(f"Wrote {target}")
