// LUT-based colormap endpoint tests. The LUT is generated by
// scripts/py/gen_colormaps.py from matplotlib; these tests pin the reference
// endpoints so a regeneration that drifts from matplotlib will be caught.

import { describe, it, expect } from 'vitest';
import { viridis, cividis, rdbu } from '../../shared/js/render/colormaps.js';

function near(actual, expected, tol = 2) {
  return Math.abs(actual - expected) <= tol;
}

describe('viridis: matplotlib endpoint match', () => {
  it('viridis(0) is rgb(68, 1, 84) within 2 units per channel', () => {
    const c = viridis(0);
    expect(near(c.r, 68, 2)).toBe(true);
    expect(near(c.g, 1, 2)).toBe(true);
    expect(near(c.b, 84, 2)).toBe(true);
  });

  it('viridis(1) is rgb(253, 231, 37) within 2 units per channel', () => {
    const c = viridis(1);
    expect(near(c.r, 253, 2)).toBe(true);
    expect(near(c.g, 231, 2)).toBe(true);
    expect(near(c.b, 37, 2)).toBe(true);
  });

  it('viridis(0.5) is a green-blue midpoint with G in [120, 160], R in [25, 65]', () => {
    const c = viridis(0.5);
    expect(c.r).toBeGreaterThan(25);
    expect(c.r).toBeLessThan(65);
    expect(c.g).toBeGreaterThan(120);
    expect(c.g).toBeLessThan(160);
  });
});

describe('cividis: monotone in R channel', () => {
  it('cividis(0).r < cividis(1).r (cividis ramps blue -> yellow)', () => {
    expect(cividis(0).r).toBeLessThan(cividis(1).r);
  });
});

describe('rdbu (diverging): mid is near-white, endpoints opposite hues', () => {
  it('rdbu(0.5) is in the high-luminance zone (all channels > 200)', () => {
    const c = rdbu(0.5);
    expect(c.r).toBeGreaterThan(200);
    expect(c.g).toBeGreaterThan(200);
    expect(c.b).toBeGreaterThan(200);
  });

  it('rdbu(0) is blue-dominant; rdbu(1) is red-dominant', () => {
    const c0 = rdbu(0);
    expect(c0.b).toBeGreaterThan(c0.r);
    const c1 = rdbu(1);
    expect(c1.r).toBeGreaterThan(c1.b);
  });
});

describe('interpolation: no NaN for any t in [0, 1]', () => {
  it('256 evenly spaced samples produce finite integer rgb', () => {
    for (let i = 0; i <= 256; i += 1) {
      const t = i / 256;
      for (const fn of [viridis, cividis, rdbu]) {
        const c = fn(t);
        expect(Number.isFinite(c.r) && Number.isFinite(c.g) && Number.isFinite(c.b)).toBe(true);
        expect(c.r).toBeGreaterThanOrEqual(0);
        expect(c.r).toBeLessThanOrEqual(255);
        expect(c.g).toBeGreaterThanOrEqual(0);
        expect(c.g).toBeLessThanOrEqual(255);
        expect(c.b).toBeGreaterThanOrEqual(0);
        expect(c.b).toBeLessThanOrEqual(255);
      }
    }
  });
});
