import { chromium } from 'playwright';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { startStaticServer } from '../tests/helpers/static-server.mjs';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { server, url } = await startStaticServer(ROOT);
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 860 } });
const errs = [];
p.on('pageerror', (e) => errs.push(String(e)));
p.on('console', (m) => { if (m.type() === 'error') errs.push('c:' + m.text()); });
await p.goto(url + '/index.html', { waitUntil: 'load', timeout: 20000 });
await p.evaluate(() => { for (const el of document.body.children) { if (el.id !== 'ambient') el.style.visibility = 'hidden'; } });
await p.waitForTimeout(1200);
await p.screenshot({ path: '/tmp/amb-A.png' });
await p.waitForTimeout(3500);
await p.screenshot({ path: '/tmp/amb-B.png' });
const d = await p.evaluate(() => {
  const c = document.getElementById('ambient');
  if (!c) return { ok: false };
  const g = c.getContext('2d');
  const s = c.width, im = g.getImageData(0, 0, Math.min(120, c.width), Math.min(120, c.height)).data;
  let lum = 0; for (let i = 0; i < im.length; i += 64) lum += im[i] + im[i + 1] + im[i + 2];
  return { ok: true, w: c.width, h: c.height, lum };
});
console.log('AMB', JSON.stringify(d), 'errs', errs.length ? errs.join(' | ') : 'none');
await b.close(); await server.closePromise();
